services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${DATABASE_SERVER_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?DATABASE_PASSWORD not set. Please define it}
      POSTGRES_USER: app_dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_dev", "-d", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
