name: Setup PHP
description: Setup PHP with caching

inputs:
  php-version:
    description: PHP version to setup
    required: false
    default: "8.5"

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
