name: Application Tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  application:
    name: Application Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: 3ur2jQH3VHVl
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          coverage: none

      - name: Install dependencies
        uses: ./.github/actions/bootstrap-composer

      - name: Run migrations
        env:
          APP_ENV: test
          DATABASE_URL: "postgresql://app:3ur2jQH3VHVl@127.0.0.1:5432/app?serverVersion=16&charset=utf8"
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run application tests
        env:
          APP_ENV: test
          DATABASE_URL: "postgresql://app:3ur2jQH3VHVl@127.0.0.1:5432/app?serverVersion=16&charset=utf8"
        run: composer tests --testsuite application
