name: PHP CS Fixer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install dependencies
        uses: ./.github/actions/bootstrap-composer

      - name: Run PHP CS Fixer
        run: composer cs:check
