name: PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install dependencies
        uses: ./.github/actions/bootstrap-composer

      - name: Run PHPStan
        run: composer phpstan:analyze
